### ISSUE TITLE
need a way to pass in additional options to the underlying commands

### ISSUE THREAD

**Issue by vinyar** [jeremiahsnapp/dev-lxc#1]
For example, I was getting some strange GPG error
`ERROR: Unable to fetch GPG key from keyserver.`

There are a couple of ways to investigate it - by passing the debug flag to the lxc-create command or by passing the `--no-validate`. 

As far as I could tell, dev-lxc wrapper doesn't allow options to be passed to underlying commands.

**Comment by jeremiahsnapp** [comment]
Thanks for the suggestion! Resolved by https://github.com/jeremiahsnapp/dev-lxc/commit/72f069b785cc9c6eca46e43909ac11fbcaf38e46
